---
name: 'Publish master to Ansible Galaxy'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'
      - name: 'galaxy'
        uses: 'ansible/ansible-publish-action@v1.0.0'
        with:
          api_key: '${{ secrets.ansible_galaxy_api_key }}'